Update README.md
UniqueNetwork/unique-types-js pull request #1
Opened 2022-03-05 16:42 UTC by fend25

2022-04-26 08:00 UTC, CertainLach requested changes

2022-04-26 08:00 UTC, CertainLach commented on README.md
> +      "@polkadot/types/lookup": ["node_modules/@unique-nft/types/types-lookup"]
node_modules точно нужно?
typescript же из коробки должен уметь резолвить как node_modules, так и всякие yarn pnp

2022-04-29 11:31 UTC, fend25 commented on README.md
> +      "@polkadot/types/lookup": ["node_modules/@unique-nft/types/types-lookup"]
Нужно, только что проверил - не работает без него, даже без "node_modules" в exclude.

Конфиг, на котором я проверял:

{
  "compilerOptions": {
    "moduleResolution": "Node",
    "module": "CommonJS",
    "skipLibCheck": true,
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "incremental": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,

    "baseUrl": ".",
    "rootDir": ".",
    "paths": {
      "@polkadot/types/lookup": ["node_modules/@unique-nft/types/types-lookup"]
    }
  },
  "exclude": ["node_modules", "dist", "test"]
}

2022-04-29 12:01 UTC, CertainLach approved these changes

2022-04-29 12:01 UTC, merged